// // // // // // // // // // // // // // // // // /////////////////////////
// LandUtil.as 陆地工具
// Macromedia ActionScript Implementation of the Class PiecePosition
// Generated by Enterprise Architect
// Created on:      11-五月-2012 15:20:02
// Original author: ZengFeng
// // // // // // // // // // // // // // // // // /////////////////////////
package worlds.maps.layers.lands
{
    import worlds.maps.configs.LandConfig;

    /**
     * @author ZengFeng (Eamil:zengfeng75[AT])163.com 2012-5-11
     */
    public class LandUtil
    {
        // ===========================
        // 坐标转换
        // ===========================
        /** 陆地网格转地图坐标 */
        public static function gridToMapX(gridX : int) : int
        {
            return LandConfig.GRID_ITEM_WIDTH * gridX;
        }

        public static function gridToMapY(gridY : int) : int
        {
            return LandConfig.GRID_ITEM_HEIGHT * gridY;
        }

        /** 地图坐标转陆地网格 */
        public static function mapToGridX(mapX : int) : int
        {
            return int(mapX / LandConfig.GRID_ITEM_WIDTH);
        }

        public static function mapToGridY(mapY : int) : int
        {
            return int(mapY / LandConfig.GRID_ITEM_HEIGHT);
        }

        /** 地图块转地图坐标 */
        public static function pieceToMapX(pieceX : int) : int
        {
            return pieceX * LandConfig.PIECE_WIDTH;
        }

        public static function pieceToMapY(pieceY : int) : int
        {
            return pieceY * LandConfig.PIECE_HEIGHT;
        }

        /** 地图坐标转地图块 */
        public static function mapToPieceX(mapX : int) : int
        {
            return int(mapX / LandConfig.PIECE_WIDTH);
        }

        public static function mapToPieceY(mapY : int) : int
        {
            return int(mapY / LandConfig.PIECE_HEIGHT);
        }

        // ===========================
        // 地图块KEY,陆地区域单元格KEY
        // ===========================
        /** 地图块KEY */
        public static function getPieceKey(pieceX : int, pieceY : int) : String
        {
            return pieceY + "_" + pieceX;
        }

        /** 陆地区域单元格KEY */
        public static function getGridItemKey(gridItemX : int, gridItemY : int) : String
        {
            return gridItemY + "_" + gridItemX;
        }
        
    }
}
