// // // // // /////////////////////////////////////////////////
// GridItemPool.as
// Macromedia ActionScript Implementation of the Class GridItemPool
// Generated by Enterprise Architect
// Created on:      11-五月-2012 15:20:01
// Original author: ZengFeng
// // // // // /////////////////////////////////////////////////
package worlds.auxiliarys.grids
{
    /**
     * 区块单元格池
     * @author ZengFeng
     * @version 1.0
     * @updated 11-五月-2012 15:22:39
     */
    public class GridItemPool
    {
        /** 单例对像 */
        private static var _instance : GridItemPool;

        /** 获取单例对像 */
        static public function get instance() : GridItemPool
        {
            if (_instance == null)
            {
                _instance = new GridItemPool(new Singleton());
            }
            return _instance;
        }

        private var list : Vector.<GridItem> = new Vector.<GridItem>();

        function GridItemPool(singleton : Singleton)
        {
        }

        public function getObject() : GridItem
        {
            if (list.length > 0)
            {
                return list.pop();
            }
            return new GridItem();
        }

        /**
         * 
         * @param gridItem
         */
        public function destoryObject(gridItem : GridItem) : void
        {
            if (gridItem == null) return;
            if (list.indexOf(gridItem) != -1) return;
            gridItem.data = null;
            list.push(gridItem);
        }
    }
    // end GridItemPool
}
class Singleton
{
}