// // // // // // // // // // // // // // // // ///////////////////////////
// Grid.as
// Macromedia ActionScript Implementation of the Class Grid
// Generated by Enterprise Architect
// Created on:      11-五月-2012 15:20:01
// Original author: ZengFeng
// // // // // // // // // // // // // // // // ///////////////////////////
package worlds.auxiliarys.grids
{
	import flash.utils.getTimer;

    /**
     * 区块网格
     * @author ZengFeng
     * @version 1.0
     * @updated 11-五月-2012 15:22:39
     */
    public class Grid
    {
        public var items : Vector.<GridItem> = new Vector.<GridItem>();
        public var builderGridStrategy : AbstractGenerateGridStrategy;
        public var gridItemPool : GridItemPool;
        public var countX : int;
        public var countY : int;

        function Grid()
        {
            gridItemPool = GridItemPool.instance;
        }

        /**
         * 重新生成网格
         * 
         * @param width    网格总宽度
         * @param height    网格总高度
         * @param itemPresetWidth    单元格预设宽度
         * @param itemPresetHeight    单元格预设高度
         * @param builderGridStrategy    生成网格策略
         */
        public function reset(width : int, height : int, itemPresetWidth : int, itemPresetHeight : int, builderGridStrategyClass : Class) : void
        {
            
            trace("destoryStart",getTimer());
            // 析构
            destory();
            trace("destoryOver",getTimer());
            // 实例化生成策略
            if (builderGridStrategy == null || builderGridStrategy is builderGridStrategyClass == false)
            {
                builderGridStrategy = new builderGridStrategyClass();
            }
            // 生成网格
            builderGridStrategy.generateGrid(width, height, itemPresetWidth, itemPresetHeight, items, null);
            // 取得行列
            countX = Math.ceil(width / itemPresetWidth) + 1;
            countY = Math.ceil(height / itemPresetHeight) + 1;
        }

        /**
         * 析构
         */
        public function destory() : void
        {
            while (items.length > 0)
            {
                gridItemPool.destoryObject(items.pop());
            }
        }
    }
    // end Grid
}