// /////////////////////////////////////////////////////////
// GridItem.as
// Macromedia ActionScript Implementation of the Class GridItem
// Generated by Enterprise Architect
// Created on:      11-五月-2012 15:20:01
// Original author: ZengFeng
// /////////////////////////////////////////////////////////
package worlds.auxiliarys.grids
{
    /**
     * 区块网格的单元格
     * @author ZengFeng
     * @version 1.0
     * @updated 11-五月-2012 15:22:39
     */
    public class GridItem
    {
        public var mapX : int;
        public var mapY : int;
        public var width : int;
        public var height : int;
        public var itemX : int;
        public var itemY : int;
        public var isNormalSize:Boolean = true;
        public var data:*;

        function GridItem()
        {
        }
    }
    // end GridItem
}