// // // // // // // // // // // // // /////////////////////////////////
// BitmapPool.as
// Macromedia ActionScript Implementation of the Class BitmapPool
// Generated by Enterprise Architect
// Created on:      11-五月-2012 15:20:01
// Original author: ZengFeng
// // // // // // // // // // // // // /////////////////////////////////
package worlds.auxiliarys.loads.pools
{
    import flash.display.Loader;

    /**
     * @author ZengFeng
     * @version 1.0
     * @updated 11-五月-2012 15:22:38
     */
    public class LoaderPool
    {
        /** 单例对像 */
        private static var _instance : LoaderPool;

        /** 获取单例对像 */
        static public function get instance() : LoaderPool
        {
            if (_instance == null)
            {
                _instance = new LoaderPool(new Singleton());
            }
            return _instance;
        }

        private const MAX_COUNT : int = 2000;
        public var list : Vector.<Loader> = new Vector.<Loader>();

        function LoaderPool(singleton : Singleton)
        {
            singleton;
            for(var i:int = 0; i < 100; i++)
            {
                list.push(new Loader());
            }
        }

        public function getObject() : Loader
        {
            if (list.length > 0)
            {
                return list.pop();
            }
            return new Loader();
        }

        /**
         * 
         * @param bitmap
         */
        public function destoryObject(loader : Loader, cancel : Boolean, gc : Boolean = false) : void
        {
            if (loader == null) return;
            if (list.indexOf(loader) != -1) return;
            if (cancel == false) loader.unloadAndStop(gc);
            if (list.length < MAX_COUNT) list.push(loader);
        }
    }
}
class Singleton
{
}