// // // // // // // // // /////////////////////////////////////////
// BitmapPool.as
// Macromedia ActionScript Implementation of the Class BitmapPool
// Generated by Enterprise Architect
// Created on:      11-五月-2012 15:20:01
// Original author: ZengFeng
// // // // // // // // // /////////////////////////////////////////
package worlds.auxiliarys.loads.pools
{
    import flash.net.URLRequest;

    /**
     * @author ZengFeng
     * @version 1.0
     * @updated 11-五月-2012 15:22:38
     */
    public class URLRequestPool
    {
        /** 单例对像 */
        private static var _instance : URLRequestPool;

        /** 获取单例对像 */
        static public function get instance() : URLRequestPool
        {
            if (_instance == null)
            {
                _instance = new URLRequestPool(new Singleton());
            }
            return _instance;
        }

        private const MAX_COUNT : int =2000;
        private var list : Vector.<URLRequest> = new Vector.<URLRequest>();

        function URLRequestPool(singleton : Singleton)
        {
			singleton;
            for(var i:int = 0; i < 100; i++)
            {
                list.push(new URLRequest());
            }
        }

        public function getObject() : URLRequest
        {
            if (list.length > 0)
            {
                return list.pop();
            }
            return new URLRequest();
        }

        /**
         * 
         * @param bitmap
         */
        public function destoryObject(urlRequest : URLRequest) : void
        {
            if (urlRequest == null) return;
            if (list.indexOf(urlRequest) != -1) return;
            urlRequest.url = null;
            if (list.length < MAX_COUNT) list.push(urlRequest);
        }
    }
    // end BitmapPool
}
class Singleton
{
}