// // // // // // ///////////////////////////////////////////////
// PiecePosition.as
// Macromedia ActionScript Implementation of the Class PiecePosition
// Generated by Enterprise Architect
// Created on:      11-五月-2012 15:20:02
// Original author: ZengFeng
// // // // // // ///////////////////////////////////////////////
package worlds.maps.layers.lands.pieces
{
    import worlds.maps.layers.lands.pools.PiecePositionPool;

    /**
     * @author ZengFeng
     * @version 1.0
     * @created 11-五月-2012 15:20:02
     */
    public class PiecePosition
    {
        public var pieceX : int;
        public var pieceY : int;
        public var mapX : int;
        public var mapY : int;
        public var key : String;

        function PiecePosition()
        {
        }

        public function dispose() : void
        {
            pieceX = NaN;
            pieceY = NaN;
            mapX = NaN;
            mapY = NaN;
            key = null;
            PiecePositionPool.instance.destoryObject(this, true);
        }
    }
}